app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime



class User(UserMixin,db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(200),index = True)
    email = db.Column(db.String(255),unique = True,index = True)
    bio = db.Column(db.String(255))
    profile_path = db.Column(db.String())
    pass_code_secure = db.Column(db.String(255))
    

    @property
    def password(self):
        raise AttributeError('you cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_code_secure = generate_password_hash(password)

    def verify_password(self,password):
        return check_password_hash(self.pass_code_secure,password)

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))

    def __repr__(self):
        return f'User {self.username}'

class Pitch(db.Model):
    __tablename__ = 'pitch'

    id = db.Column(db.Integer,primary_key = True)
    pitch_title = db.Column(db.String(255))
    pitch_body = db.Column(db.String(255))
    posted = db.Column(db.DateTime,default = datetime.utcnow)
    user = db.Column(db.String(255))
    category = db.Column(db.String(255))
    

    def save_pitch(self):
        db.session.add(self)
        db.session.commit()
    @classmethod
    def get_user_pitch(cls,name):
        pitches = Pitch.query.filter_by(user = name).all()

        return pitches

    @classmethod
    def get_pitch_category(cls,categoryName):
        pitch_cat_list = Pitch.query.filter_by(category = categoryName)

        return pitch_cat_list

    @classmethod
    def get_all_pitch(cls):
        pitch_list = Pitch.query.all()

        return pitch_list

class Comment(db.Model):
    __tablename__ = 'comment'

    id = db.Column(db.Integer,primary_key = True)
    pitch_id = db.Column(db.Integer)
    posted = db.Column(db.DateTime, default = datetime.utcnow)
    comment = db.Column(db.String(255))
    user = db.Column(db.String(255))

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_pitch_comment(cls,id):
        comment = Comment.query.filter_by(pitch_id = id)

        return comment

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,SelectField,BooleanField,TextAreaField ,PasswordField,SubmitField
from wtforms.validators import Required,Email,EqualTo
from ..models import User
from wtforms import ValidationError

class UpdateProfile(FlaskForm):
    bio = TextAreaField('tell us about yourself.',validators = [Required()])
    submit = SubmitField('Submit')

class NewPitch(FlaskForm):
    title = StringField('pitch title',validators = [Required()])
    body = TextAreaField('write the pitch',validators = [Required()])
    category = SelectField(u'input category', choices =[('Business','Business'),('Sport','Sport'),('Religious','Religious'),('Educational','Educational')])
    submit = SubmitField('Submit')

class CommentForm(FlaskForm):
    comment = TextAreaField('write a comment', validators=[Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap 
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail


bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
photos = UploadSet('photos',IMAGES)
mail = Mail()

def create_app(config_name):
    app = Flask(__name__)

    #creating the app configuration
    app.config.from_object(config_options[config_name])


    # intilizing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    
    # configure uploadset
    configure_uploads(app,photos)

    # registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    # setting config

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views

app/main/views.py
from flask import render_template,abort,request,redirect,url_for
from . import main
from flask_login import login_required, current_user
from ..models import User,Pitch,Comment
from .forms import UpdateProfile,NewPitch,CommentForm
from .. import db,photos


@main.route('/')
def index():

    title= "home"

    pitches = Pitch.get_all_pitch()
    business = Pitch.get_pitch_category("Business")
    sport = Pitch.get_pitch_category("Sport")
    education = Pitch.get_pitch_category("Educational")
    religious = Pitch.get_pitch_category("Religious")

    return render_template("index.html",business = business,sport = sport,education = education,religious = religious ,title=title,pitches = pitches)


@main.route('/user/<uname>')
@login_required
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)
    pitch = Pitch.get_user_pitch(user.username)
    return render_template("profile/profile.html",user = user,pitch = pitch)

@main.route('/user/<uname>/update', methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)
    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()
        return redirect(url_for('.profile',uname = user.username))
    
    return render_template('profile/update.html',form = form)

@main.route('/pitch/new/<uname>', methods = ['GET','POST'])
@login_required
def new_pitch(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)
    form = NewPitch()
    if form.validate_on_submit():
        title = form.title.data
        pitch = form.body.data
        category = form.category.data

        new_pitch = Pitch(pitch_title = title,pitch_body = pitch,category = category,user = current_user.username )

        new_pitch.save_pitch()
        return redirect(url_for('.profile',uname = current_user.username))
    title="create new pitch"
    return render_template('new_pitch.html',title = title,pitch_form = form,user = user)

@main.route('/pitch/comment/new/<int:id>', methods = ['GET','POST'])
@login_required
def new_comment(id):
    pitch = Pitch.query.filter_by(id = id ).first()
    form = CommentForm()
    if form.validate_on_submit():
        comment = form.comment.data

        new_comment = Comment(pitch_id = pitch.id, comment = comment, user = current_user.username)

        new_comment.save_comment()
        return redirect(url_for('.pitch',id = pitch.id))

    title = f'{pitch.pitch_title} comment'
    return render_template('comment.html',title = title, comment_form = form,pitch = pitch)

@main.route('/pitch/<id>')
@login_required
def pitch(id):
    pitch = Pitch.query.filter_by(id = id).first()

    comment = Comment.get_pitch_comment(pitch.id)
    return render_template('pitch.html',pitch = pitch, comment = comment)


@main.route('/user/<uname>/update/pic', methods = ['Post'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photo/{filename}'
        user.profile_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname = uname))

app/templates/base.html
<!DOCTYPE html>
{% extends 'bootstrap/base.html'%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href=" {{url_for('static',filename='css/bootstrap.css')}} ">
    <title>pitch</title>

    <style>
        body {
            margin: 0;
        }
        
        ul {
            list-style-type: none;
            margin: 0;
            padding: 0;
            width: 25%;
            background-color: #f1f1f1;
            position: fixed;
            height: 100%;
            overflow: auto;
        }
        
        li a {
            display: block;
            color: #000;
            padding: 8px 16px;
            text-decoration: none;
        }
        
        li a.active {
            background-color: #4CAF50;
            color: white;
        }
        
        li a:hover:not(.active) {
            background-color: #555;
            color: white;
        }
        
    </style>
</head>
<body>
    <div class="row">
        <div class="col-md-3">
            <div class="nav">
                <ul>
                    <li><a href="">PitchApp</a></li>
                    
                    <li><a class="active" href="/">Home</a></li>
                    <li><a href="#contact">Contact</a></li>
                    <li><a href="#about">About</a></li>
                    {% if current_user.is_authenticated%}
                    <li style="color:black;padding: 15px;">{{current_user.username}}</li>
                    <li> <a href="{{url_for('main.profile',uname = current_user.username)}}">Profile</a> </li>
                    <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                    {% else%}
                    <li><a href="{{url_for('auth.login')}}">Sign In</a></li>
                    {% endif%}
                </ul>
                
        
            </div>
        </div>
        <div class="col-md-9">
            {% block content%}
            {% endblock%}
        </div>
    </div>
</body>

app/templates/comment.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf%}
{% block styles %}
{{super()}}
<link rel="stylesheet" type='text/css' href="{{url_for('static',filename = 'css/newPitch.css')}}">
{% endblock styles %}
{% block content%}

    <div class="container">
        <h2>write your comment</h2>
        <p>pitch title: {{pitch.pitch_title}}</p>
        {{wtf.quick_form(comment_form)}}
    </div>
{% endblock%}

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=Cormorant+Garamond|Parisienne|Playfair+Display+SC&display=swap" rel="stylesheet"> 
    <link rel="stylesheet" href="{{url_for('static',filename='css/bootstrap.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
    <title>pitch</title>

    <style>
        body {
            margin: 0;
            background-color: black;
            background-image: url("https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.setaswall.com%2Fwp-content%2Fuploads%2F2017%2F07%2FBlack-Wallpapers-14-1440-x-900.png&f=1&nofb=1");
            background-size: contain;
        
        }
        
        ul {
            list-style-type: none;
            margin: 0;
            padding: 0;
            width: 15%;
            background-image: url("https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP.oJDHeDvGYhULfNxvkyBwygHaNK%26pid%3DApi&f=1");
            background-size: cover;
            background-repeat: no-repeat;
            background-color: rgb(100, 6, 6);
            position: fixed;
            height: 100%;
            overflow: auto;
        }
        
        li a {
            display: block;
            color: silver;
            padding: 8px 16px;
            text-decoration: none;
        }
        
        li a.active {
            background-color: rgb(11, 11, 36);
            color: white;
        }
        
        li a:hover:not(.active) {
            background-color: rgba(0, 0, 0, 0.767);
            color: white;
        }
        h1{
            color:rgb(177, 177, 177);
            font-size: 70px;
            font-family: 'Playfair Display SC', serif;
        }
        .card{
            background-color: rgb(87, 83, 83);
            color: black;
            font-size: 20px;
        }
        .card-header{
            background-color: black;
            color:white;
            font-size: 25px;
        }
        h3{
            color:rgb(233, 233, 233);
            font-size: 40px;
            font-family: 'Cormorant Garamond', serif;
        }
    </style>
</head>
<body>
    <div class="row">
        <div class="col-md-3">
            <div class="nav">
                <ul>
                    <li><a href="">PitchApp</a></li>
                    
                    <li><a class="active" href="/">Home</a></li>
                    
                    
                    
                    {% if current_user.is_authenticated%}
                    <li style="color:black;padding: 15px;">{{current_user.username}}</li>
                    <li><a href="/pitch/new/{{current_user.username}}"> Add new pitch</a></li>
                    <li> <a href="{{url_for('main.profile',uname = current_user.username)}}">Profile</a> </li>
                    
                    <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                    {% else%}
                    <li><a href="{{url_for('auth.login')}}">Sign In</a></li>
                    {% endif%}
                </ul>
                
        
            </div>
        </div>
           
        <div class="col-md-9">
                <h1>THE-PITCH-APP</h1><br><br>
            <h3><b>business pitch</b></h3>
            <div class="row">
                {% for bs in business %}
                    <div class="col-md 4">
                        <div class="card">
                            <div class="card-header">
                                <p>{{bs.category}}</p>
                            </div>
                            <div class="card-body">
                                <p> {{bs.pitch_body}} </p>
                            </div>
                            <div class="card-footer">
                                <a href="/pitch/{{bs.id}}">Write a comment</a>
                                
                            </div>
                        </div>
                    </div>
                {% endfor%}
            </div>
            <h3><b>educational pitches</b></h3>
            <div class="row">
                {% for educ in education %}
                    <div class="col-md 4">
                        <div class="card">
                            <div class="card-header">
                                <p>{{educ.category}}</p>
                            </div>
                            <div class="card-body">
                                <p> {{educ.pitch_body}} </p>
                            </div>
                            <div class="card-footer">
                                <a href="/pitch/{{educ.id}}">Write a comment</a>
                                
                            </div>
                        </div>
                    </div>
                {% endfor%}
            </div>
            <h3><b>sport pitches</b></h3>
            <div class="row">
                {% for sprt in sport %}
                    <div class="col-md 4">
                        <div class="card">
                            <div class="card-header">
                                <p>{{sprt.category}}</p>
                            </div>
                            <div class="card-body">
                                <p> {{sprt.pitch_body}} </p>
                            </div>
                            <div class="card-footer">
                                <a href="/pitch/{{sprt.id}}">Write a comment</a>
                                
                            </div>
                        </div>
                    </div>
                {% endfor%}
            </div>
            <h3><b>Religious</b></h3>
            <div class="row">
                    {% for rel in religious %}
                        <div class="col-md 4">
                            <div class="card">
                                <div class="card-header">
                                    <p>{{rel.category}}</p>
                                </div>
                                <div class="card-body">
                                    <p> {{rel.pitch_body}} </p>
                                </div>
                                <div class="card-footer">
                                    <a href="/pitch/{{rel.id}}">Write a comment</a>
                                    
                                </div>
                            </div>
                        </div>
                    {% endfor%}
                </div>
        
        </div>
    </div>
    <!-- navbar -->
   
    
</body>
</html>

app/templates/new_pitch.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf%}

{% block styles %}
{{super()}}
<link rel="stylesheet" type='text/css' href="{{url_for('static',filename = 'css/newPitch.css')}}">
{% endblock styles %}

{% block content%}
    <body>
    <div class="container">
        <h2>Add new pitch.</h2>

            {{wtf.quick_form(pitch_form)}}
    </div>
    </body>
{% endblock%}

app/templates/pitch.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{{url_for('static',filename='css/bootstrap.css')}}">
    <title>Document</title>
    <style>
         body {
            margin: 0;
            background-color: black;
            background-image: url(https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.setaswall.com%2Fwp-content%2Fuploads%2F2017%2F07%2FBlack-Wallpapers-14-1440-x-900.png&f=1&nofb=1);
            background-size: contain;
            color:white;
            font-size: 35px;
        }
        
        ul {
            list-style-type: none;
            margin: 0;
            padding: 0;
            width: 15%;
            background-image: url(https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP.oJDHeDvGYhULfNxvkyBwygHaNK%26pid%3DApi&f=1);
            background-size: cover;
            background-repeat: no-repeat;
            background-color: rgb(100, 6, 6);
            position: fixed;
            height: 100%;
            overflow: auto;
        }
        
        li a {
            display: block;
            color: silver;
            padding: 8px 16px;
            text-decoration: none;
        }
        
        li a.active {
            background-color: rgb(11, 11, 36);
            color: white;
        }
        
        li a:hover:not(.active) {
            background-color: rgba(0, 0, 0, 0.767);
            color: white;
        }
        h1{
            color:rgb(177, 177, 177);
            font-size: 70px;
            font-family: 'Playfair Display SC', serif;
        }
        .card{
            background-color: rgb(87, 83, 83);
            color: black;
            font-size: 20px;
            margin-top: 10px;
        }
        .card-header{
            background-color: black;
            color:white;
            font-size: 25px;
        }
        h3{
            color:rgb(233, 233, 233);
            font-size: 40px;
            font-family: 'Cormorant Garamond', serif;
        }
        .card-footer{
            background-color: black;
            color:silver;
            font-size: 25px;
        }
    </style>
</head>
<body>
    <div class="row">
        <div class="col-md-3">
            <div class="nav">
                <ul>
                    <li><a href="">PitchApp</a></li>
                    
                    <li><a class="active" href="/">Home</a></li>
                    {% if current_user.is_authenticated%}
                    <li><a href="/pitch/new/{{current_user.username}}"> Add new pitch</a></li>
                    <li style="color:black;padding: 15px;">{{current_user.username}}</li>
                    <li> <a href="{{url_for('main.profile',uname = current_user.username)}}">Profile</a> </li>
                    
                    <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                    {% else%}
                    <li><a href="{{url_for('auth.login')}}">Sign In</a></li>
                    {% endif%}
                </ul>
                
        
            </div>
        </div>
        <div class="col-md-9" style="margin-top: 20px">
            <p> The {{pitch.title}} pitch</p>
            <div class="row">
                    <div class="col-md 4">
                        <div class="card">
                            <div class="card-body">
                                <p> {{pitch.pitch_body}} </p>
                                <center><p><i>posted by </i>{{pitch.user}}</p></center>
                            </div>

                            <div class="card-footer">
                                <p>posted on {{pitch.posted}}</p>
                                
                            </div>
                        </div>
                    </div>
            </div>
            <p>comments</p>
            <p> <button><a href="/pitch/comment/new/{{pitch.id}}">add comment</a> </button></p>
            
                {% for com in comment %}
                    
                        <div class="card">
                            <p>{{com.comment}}</p>
                            
                            <p><i>posted by</i> {{com.user}} <i>on </i> {{com.posted}}</p>
                            
                        </div>
                    
                {% endfor%}

             
            
        </div>
    </div>
</body>
</html>

app/templates/profile/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{{url_for('static',filename='css/bootstrap.css')}}">
    <title>Document</title>
</head>
<style>
        body{
            margin: 0;
            background-color: black;
            background-image: url(https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.setaswall.com%2Fwp-content%2Fuploads%2F2017%2F07%2FBlack-Wallpapers-14-1440-x-900.png&f=1&nofb=1);
            background-size: contain;
        }
        h2{
            color:rgb(233, 233, 233);
            font-size: 40px;
            font-family: 'Cormorant Garamond', serif;
        }
        p{
            
            color:black;
            font-size: 25px;
        }

</style>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-4" style="margin-top:20px;">

                {% if user.profile_path%}
                    <img src="{{url_for('static',filename=user.profile_path)}}" alt="" class="img-thumbnail">
                    {{user.profile_path}}
                {% else%}
                    <p>No profile picture</p>
                {% endif%}
                {% if user == current_user %}
                    <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

                    <input type="file"  name="photo" class="form-control" required>
                    <input type="submit">
                    </form>
                {% endif %}

            </div>
            <div class="col-md-4"></div>
            <div class ="col-md-4">
                <h2> USERNAME: {{user.username| capitalize}} </h2>

                {% if user.bio%}
                    <p>YOUR BIO:{{user.bio}} </p>
                {% else%}
                    <p> {{user.username| capitalize}} has no bio</p>
                {% endif%}
            </div>
        </div><br><br><br>
        {% if user == current_user%}
            <button class="btn btn-primary"><a href=" {{url_for('main.update_profile',uname = user.username)}}"><b style="color:white;font-size: 30px;">Edit profile</b></a></button>
        {% endif%}

        <center><p>pitches</p></center>
        <div class="row">
            {% if pitch%}
                {% for pit in pitch%}
                    <div class="col-md-3" style="margin-bottom:60px;">
                        <div class="card">
                            <div class="card-title">
                                <p><i>pitch title</i> {{pit.pitch_title}}</p>
                            </div>
                            <div class="card-body">
                                <p>{{pit.pitch_body}}</p>
                                <p><i>posted on</i> {{pit.posted}}</p>
                            </div>
                        </div>
                    </div>
                {% endfor%}
            {% else%}
                <h3> your have no pitches of your own</h3>
                <a href="/pitch/new/{{current_user.username}}">write a pitch</a>
            {% endif%}
        </div>
       
                
    </div>
</body>
</html>

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block styles %}
{{super()}}
<link rel="stylesheet" type='text/css' href="{{url_for('static',filename = 'css/newPitch.css')}}">
{% endblock styles %}


{% block content%}
  <div class="container">
    <h2>Add your biography..</h2>
      {{wtf.quick_form(form)}}
  </div>
{% endblock%}